language: python
python: "3.6"

before_install:
  - pip install --upgrade pip==18.1
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

install:
  - source $HOME/.poetry/env
  - poetry install

script:
  - mypy packagr --ignore-missing-imports

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master