language: python
python: "3.6"

install:
  - echo "hello"

before_deploy:
  - pip install --upgrade pip==18.1
  - pip install poetry
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
  - poetry build

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master